spring:
  application:
    name: ai.service

  datasource:
    url: jdbc:postgresql://localhost:5433/ai-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  ai:
    google:
      genai:
        embedding:
          api-key: ${GEMINI_KEY}
          text:
            options:
              model: text-embedding-004
              dimensions: 768
    vectorstore:
      pgvector:
        dimensions: 768
        distance-type: COSINE_DISTANCE

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: false

  config:
    import: optional:configserver:http://localhost:8095

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: hotel-exchange
    queue:
      name: rating-queue
    routing:
      key: hotel.rating

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

server:
  port: 8096