spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8095

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8443/realms/hotel-microservice

server:
  port: 8094

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO