spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8095

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8443/realms/hotel-microservice/protocol/openid-connect/certs

server:
  port: 8094

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO